# Generated by Django 3.2.5 on 2021-08-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_photo',
            new_name='photo',
        ),
    ]
