# Generated by Django 3.2.5 on 2021-08-03 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guests',
            field=models.ManyToManyField(related_name='guest_at_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
